#! /usr/bin/env node

var rootpath = require('./lib/rootpath')

var fs = require('fs-sync')

var filename = rootpath('template/template.jade')
var tmt = fs.read(filename)

var chroma = require('chroma-js')

var schema = require('stalwart')

var jade = require('jade')

var xml = jade.render(tmt,
{
	filename: filename,
	pretty: '\t',

	C: chroma,
	hexa: require('stalwart/run/lib/to-hexa'),
	schema: schema,
	base16: schema.base16.colors.bg
})


0 && console.dir(schema)

fs.write(rootpath('Stalwart.tmTheme'), xml)

0 && process.stdout.write(xml + '\n')
