#! /usr/bin/env node

var root = require('./lib/rootpath')

var fs = require('fs-sync')

var filename = root('template/template.jade')
var tmt = fs.read(filename)

var chroma = require('chroma-js')
var schema = require('stalwart')

var jade = require('jade')

var xml = jade.render(tmt,
{
	filename: filename,
	pretty: true,

	C: chroma,
	schema: schema
})


1 && console.dir(schema)

fs.write(root('Stalwart.tmTheme'), xml)

0 && process.stdout.write(xml + '\n')
