#! /usr/bin/env node

var root = require('./lib/rootpath')

var watch = require('glob-watcher')

var paths = [ 'template/*' ].map(path => root(path))

var cmd = require('command-promise').so

var gen = cmd('run/gen; run/install', { cwd: root() })

watch(paths, gen)

gen()

console.info('watch is up')
