#! /usr/bin/env node

var rootpath = require('./lib/rootpath')

var watch = require('glob-watcher')

var paths = [ 'template/*' ].map(path => rootpath(path))

var cmd = require('command-promise').so

watch(paths, cmd('run/gen', { cwd: rootpath() }))

console.info('WATCH')
