#! /usr/bin/env node

var rootpath = require('./lib/rootpath')

var watch = require('glob-watcher')

var paths = [ 'template/*' ].map(path => rootpath(path))

var cmd = require('command-promise').so

watch(paths, gen)

gen()

console.info('watch is up')

function gen ()
{
	cmd('run/gen', { cwd: rootpath() })()
	.then(cmd('run/install', { cwd: rootpath() }))
	.then(() => console.info('generated'))
}
